### ISSUE TITLE
Allow party report to be between different time then the booking

### ISSUE THREAD

**Issue by Dr-Horv** [cthit/bookIT#19]
Use case: PRIT wants to book Hubben for a whole day (8 - 03) for preperations before pubcrawl. But they only want to party report the pub-time: 17 - 02.

**Comment by Ndushi** [comment]
Mostly done, needs validation! (Must be between `begin_date` and `end_date` in the main booking model)

**Comment by Ndushi** [comment]
Solved by f0bd34c38eb2297c561314ef1ca71f5f1d4759fc
