### ISSUE TITLE
24h clock in calendar view

### ISSUE THREAD

**Issue by Edholm** [cthit/bookIT#30]

**Comment by Tejpbit** [comment]
The calendar currently used probably have support for showing the current time with a line in the current day.

**Comment by Edholm** [comment]
@Tejpbit What do you mean? The current day is highlighted with a different color

**Comment by Tejpbit** [comment]
Instead of a 24h clock a horizontal bar overlaying the current day could show the current time of day. Like google calendar uses.

**Comment by lindskogen** [comment]
Get your own issue, @Tejpbit!
