### ISSUE TITLE
Medansvarig now required?

### ISSUE THREAD

**Issue by Cannonbait** [cthit/bookIT#32]
When we spoke to CUBSEC during the last Kod & Vin™, they said that it was necessary to have a medansvarig in the festanmälan for it to be valid. Do we have any information about this?

**Comment by Edholm** [comment]
https://youtu.be/9jwwWYuXI4E
That's how I read this issue :D

**Comment by Tejpbit** [comment]
We've checked with CUBSEC, and it is not required
