### ISSUE TITLE
PartyReports start/stop should only be allowed each five minutes

### ISSUE THREAD

**Issue by Vilddjur** [cthit/bookIT#33]
Chalmers only allows party reports each five minutes, i.e 12.00 12.05 and so on. If someone tries to book at 12.03 this will be rejected by chalmers servers.

**Comment by Dr-Horv** [comment]
@oskar367 this should already be resolved. By selecting closest 05 minute when booking I'm quite sure of.

**Comment by oskar367** [comment]
@Dr-Horv absolutely, but if someone does not know this they might still book at say 12:01 and then we cannot confirm this party report with chalmers

**Comment by bark** [comment]
@Kerp1 why?!?!

**Comment by Dr-Horv** [comment]
@oskar367 How do you mean?

Currently someone can book say 17:00 to 20:01 and partyreport. Then we partyreport to chalmers wiht 17 to 20:05 I think, check the source code to be sure.

**Comment by Kerp1** [comment]
@bark sorry about that, I don't know what happened. My best guess is that my phone was unlocked in my pocket and I had the issue open.

**Comment by lindskogen** [comment]
We have reduced bookings to only be allowed to an hourly basis
