### ISSUE TITLE
Selecting end time changes start time

### ISSUE THREAD

**Issue by ClausX** [cthit/bookIT#35]
When you are creating a reservation and you change time for the end date, the start dates time changes. Say I want to create a reservation starting at 13:00 and ending at 18:00. I first type in 13 as the start time, but when I type in 18 as the end time the start time changes to 01:00.  It's annoying =)

**Comment by Edholm** [comment]
@oskar367 why the `wontfix`?

**Comment by Tejpbit** [comment]
@Vilddjur why wontfix?
