### ISSUE TITLE
'Aktivitetsanmälan' should be called 'Arrangemangsanmälan'

### ISSUE THREAD

**Issue by TheFeffe** [cthit/bookIT#63]
According to chalmers own definition: https://student.portal.chalmers.se/sv/studentliv/anmalanavarrangemang/Sidor/AnmalanAvArrangemang.aspx

To reduce confusion.

**Comment by Portals** [comment]
After talking to the Vice Chairman of styrIT, we decided that 'Aktivitetsanmälan' is sufficient. According to [this document](https://chalmersstudentkar.se/wp-content/uploads/2017/08/instruktion_for_arrangorer_inom_chalmers_studentkar_0.pdf), they have called it 'Aktivitetsanmälan'. Chalmers seems to be inconsistent with the usage of the two words. 'Aktivitetsanmälan' is either way a better and more describing word than 'Festanmälan'.
